

server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3307/hanium
    url: jdbc:mysql://localhost:3306/hanium
#    username: ym
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
  elasticsearch:
    cluster:
      initial-master-nodes: ip-172-31-43-166
    uris: http://3.36.169.149:9200


jwt:
  key: Hanium_PROJ_APPLICATION-2022.key
  token.expired-time-ms: 2592000000

